/*
 * This file was generated automatically by xsubpp version 1.9508 from the
 * contents of Nodave.xs. Do not edit this file, edit Nodave.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Nodave.xs"
/*
 PERL module to library function call translations.
 
 Part of Libnodave, a free communication libray for Siemens S7 200/300/400 via
 the MPI adapter 6ES7 972-0CA22-0XAC
 or  MPI adapter 6ES7 972-0CA23-0XAC
 or  TS adapter 6ES7 972-0CA33-0XAC
 or  MPI adapter 6ES7 972-0CA11-0XAC,
 IBH/MHJ-NetLink or CPs 243, 343 and 443
 
 (C) Thomas Hergenhahn (thomas.hergenhahn@web.de) 2005

 Libnodave is free software; you can redistribute it and/or modify
 it under the terms of the GNU Library General Public License as published by
 the Free Software Foundation; either version 2, or (at your option)
 any later version.

 Libnodave is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU Library General Public License
 along with Libnodave; see the file COPYING.  If not, write to
 the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.  
*/

/*
    Changes: 05/15/06 applied bug fixes from H.-J. Beie. Thank you!
*/

#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"

#define LINUX
#include <nodave.h>

#include "const-c.inc"

typedef struct _daveInterface*	DaveInterface;
typedef struct _daveConnection*	DaveConnection;
typedef PDU*	DavePDU;
typedef daveResultSet*	DaveResultSet;

#line 58 "Nodave.c"

/* INCLUDE:  Including 'const-xs.inc' from 'Nodave.xs' */


XS(XS_Nodave_constant); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_constant)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Nodave::constant(sv)");
    SP -= items;
    {
#line 4 "const-xs.inc"
#ifdef dXSTARG
	dXSTARG; /* Faster if we have it.  */
#else
	dTARGET;
#endif
	STRLEN		len;
        int		type;
	IV		iv;
	/* NV		nv;	Uncomment this if you need to return NVs */
	/* const char	*pv;	Uncomment this if you need to return PVs */
#line 82 "Nodave.c"
	SV *	sv = ST(0);
	const char *	s = SvPV(sv, len);
#line 18 "const-xs.inc"
        /* Change this to constant(aTHX_ s, len, &iv, &nv);
           if you need to return both NVs and IVs */
	type = constant(aTHX_ s, len, &iv);
      /* Return 1 or 2 items. First is error message, or undef if no error.
           Second, if present, is found value */
        switch (type) {
        case PERL_constant_NOTFOUND:
          sv = sv_2mortal(newSVpvf("%s is not a valid Nodave macro", s));
          PUSHs(sv);
          break;
        case PERL_constant_NOTDEF:
          sv = sv_2mortal(newSVpvf(
	    "Your vendor has not defined Nodave macro %s, used", s));
          PUSHs(sv);
          break;
        case PERL_constant_ISIV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHi(iv);
          break;
	/* Uncomment this if you need to return NOs
        case PERL_constant_ISNO:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(&PL_sv_no);
          break; */
	/* Uncomment this if you need to return NVs
        case PERL_constant_ISNV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHn(nv);
          break; */
	/* Uncomment this if you need to return PVs
        case PERL_constant_ISPV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHp(pv, strlen(pv));
          break; */
	/* Uncomment this if you need to return PVNs
        case PERL_constant_ISPVN:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHp(pv, iv);
          break; */
	/* Uncomment this if you need to return SVs
        case PERL_constant_ISSV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(sv);
          break; */
	/* Uncomment this if you need to return UNDEFs
        case PERL_constant_ISUNDEF:
          break; */
	/* Uncomment this if you need to return UVs
        case PERL_constant_ISUV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHu((UV)iv);
          break; */
	/* Uncomment this if you need to return YESs
        case PERL_constant_ISYES:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(&PL_sv_yes);
          break; */
        default:
          sv = sv_2mortal(newSVpvf(
	    "Unexpected return type %d while processing Nodave macro %s, used",
               type, s));
          PUSHs(sv);
        }
#line 157 "Nodave.c"
	PUTBACK;
	return;
    }
}


/* INCLUDE: Returning to 'Nodave.xs' from 'const-xs.inc' */


XS(XS_Nodave_daveStrerror); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveStrerror)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Nodave::daveStrerror(code)");
    {
	int	code = (int)SvIV(ST(0));
	char *	RETVAL;
	dXSTARG;
#line 57 "Nodave.xs"
    RETVAL=daveStrerror(code);
#line 179 "Nodave.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveSetDebug); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveSetDebug)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Nodave::daveSetDebug(level)");
    {
	int	level = (int)SvIV(ST(0));
#line 66 "Nodave.xs"
	daveSetDebug(level);
#line 196 "Nodave.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Nodave_daveGetDebug); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveGetDebug)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Nodave::daveGetDebug()");
    {
	int	RETVAL;
	dXSTARG;
#line 73 "Nodave.xs"
	RETVAL = daveGetDebug();
#line 213 "Nodave.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveNewInterface); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveNewInterface)
{
    dXSARGS;
    if (items != 6)
	Perl_croak(aTHX_ "Usage: Nodave::daveNewInterface(r, w, name, y, x, z)");
    {
	int	r = (int)SvIV(ST(0));
	int	w = (int)SvIV(ST(1));
	char *	name = (char *)SvPV_nolen(ST(2));
	int	y = (int)SvIV(ST(3));
	int	x = (int)SvIV(ST(4));
	int	z = (int)SvIV(ST(5));
	DaveInterface	RETVAL;
#line 90 "Nodave.xs"
	_daveOSserialType sif;
	sif.rfd=r;
	sif.wfd=w;
	RETVAL = daveNewInterface(sif,name,y,x,z);
#line 239 "Nodave.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "DaveInterface", (void*)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveNewConnection); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveNewConnection)
{
    dXSARGS;
    if (items != 4)
	Perl_croak(aTHX_ "Usage: Nodave::daveNewConnection(di, y, x, z)");
    {
	DaveInterface	di;
	int	y = (int)SvIV(ST(1));
	int	x = (int)SvIV(ST(2));
	int	z = (int)SvIV(ST(3));
	DaveConnection	RETVAL;

	if (sv_derived_from(ST(0), "DaveInterface")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    di = INT2PTR(DaveInterface,tmp);
	}
	else
	    Perl_croak(aTHX_ "di is not of type DaveInterface");
#line 105 "Nodave.xs"
	RETVAL = daveNewConnection(di,y,x,z);
#line 268 "Nodave.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "DaveConnection", (void*)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveGetResponse); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveGetResponse)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Nodave::daveGetResponse(dc)");
    {
	DaveConnection	dc;
	int	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "DaveConnection")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dc = INT2PTR(DaveConnection,tmp);
	}
	else
	    Perl_croak(aTHX_ "dc is not of type DaveConnection");
#line 114 "Nodave.xs"
	RETVAL = daveGetResponse(dc);	
#line 295 "Nodave.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveSendMessage); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveSendMessage)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Nodave::daveSendMessage(dc, p)");
    {
	DaveConnection	dc;
	DavePDU	p;
	int	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "DaveConnection")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dc = INT2PTR(DaveConnection,tmp);
	}
	else
	    Perl_croak(aTHX_ "dc is not of type DaveConnection");

	if (sv_derived_from(ST(1), "DavePDU")) {
	    IV tmp = SvIV((SV*)SvRV(ST(1)));
	    p = INT2PTR(DavePDU,tmp);
	}
	else
	    Perl_croak(aTHX_ "p is not of type DavePDU");
#line 123 "Nodave.xs"
	RETVAL = daveSendMessage(dc, p);
#line 329 "Nodave.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveDumpPDU); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveDumpPDU)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Nodave::daveDumpPDU(p)");
    {
	DavePDU	p;

	if (sv_derived_from(ST(0), "DavePDU")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    p = INT2PTR(DavePDU,tmp);
	}
	else
	    Perl_croak(aTHX_ "p is not of type DavePDU");
#line 131 "Nodave.xs"
    _daveDumpPDU(p);
#line 353 "Nodave.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Nodave_daveDump); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveDump)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Nodave::daveDump(name, b, len)");
    {
	char *	name = (char *)SvPV_nolen(ST(0));
	char *	b = (char *)SvPV_nolen(ST(1));
	int	len = (int)SvIV(ST(2));
#line 139 "Nodave.xs"
    _daveDump(name,b,len);
#line 371 "Nodave.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Nodave_daveBlockName); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveBlockName)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Nodave::daveBlockName(bn)");
    {
	int	bn = (int)SvIV(ST(0));
	char *	RETVAL;
	dXSTARG;
#line 145 "Nodave.xs"
	RETVAL = daveBlockName(bn);
#line 389 "Nodave.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveAreaName); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveAreaName)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Nodave::daveAreaName(n)");
    {
	int	n = (int)SvIV(ST(0));
	char *	RETVAL;
	dXSTARG;
#line 153 "Nodave.xs"
	RETVAL = daveAreaName(n);
#line 408 "Nodave.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveSwapIed_16); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveSwapIed_16)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Nodave::daveSwapIed_16(ff)");
    {
	short	ff = (short)SvIV(ST(0));
	short	RETVAL;
	dXSTARG;
#line 161 "Nodave.xs"
	RETVAL = daveSwapIed_16(ff);
#line 427 "Nodave.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveSwapIed_32); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveSwapIed_32)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Nodave::daveSwapIed_32(ff)");
    {
	int	ff = (int)SvIV(ST(0));
	int	RETVAL;
	dXSTARG;
#line 169 "Nodave.xs"
	RETVAL = daveSwapIed_32(ff);
#line 446 "Nodave.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveGetFloatAt); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveGetFloatAt)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Nodave::daveGetFloatAt(dc, pos)");
    {
	DaveConnection	dc;
	int	pos = (int)SvIV(ST(1));
	float	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "DaveConnection")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dc = INT2PTR(DaveConnection,tmp);
	}
	else
	    Perl_croak(aTHX_ "dc is not of type DaveConnection");
#line 179 "Nodave.xs"
	RETVAL = daveGetFloatAt(dc,pos);
#line 473 "Nodave.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_toPLCfloat); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_toPLCfloat)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Nodave::toPLCfloat(f)");
    {
	float	f = (float)SvNV(ST(0));
	float	RETVAL;
	dXSTARG;
#line 187 "Nodave.xs"
	RETVAL = toPLCfloat(f);
#line 492 "Nodave.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveToPLCfloat); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveToPLCfloat)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Nodave::daveToPLCfloat(f)");
    {
	float	f = (float)SvNV(ST(0));
	int	RETVAL;
	dXSTARG;
#line 195 "Nodave.xs"
	RETVAL = daveToPLCfloat(f);
#line 511 "Nodave.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveGetS8from); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveGetS8from)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Nodave::daveGetS8from(buffer, pos)");
    {
	char *	buffer = (char *)SvPV_nolen(ST(0));
	int	pos = (int)SvIV(ST(1));
	int	RETVAL;
	dXSTARG;
#line 205 "Nodave.xs"
	RETVAL = daveGetS8from(buffer+pos);
#line 531 "Nodave.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveGetU8from); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveGetU8from)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Nodave::daveGetU8from(buffer, pos)");
    {
	char *	buffer = (char *)SvPV_nolen(ST(0));
	int	pos = (int)SvIV(ST(1));
	int	RETVAL;
	dXSTARG;
#line 215 "Nodave.xs"
	RETVAL = daveGetU8from(buffer+pos);
#line 551 "Nodave.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveGetS16from); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveGetS16from)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Nodave::daveGetS16from(buffer, pos)");
    {
	char *	buffer = (char *)SvPV_nolen(ST(0));
	int	pos = (int)SvIV(ST(1));
	int	RETVAL;
	dXSTARG;
#line 225 "Nodave.xs"
	RETVAL = daveGetS16from(buffer+pos);
#line 571 "Nodave.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveGetU16from); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveGetU16from)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Nodave::daveGetU16from(buffer, pos)");
    {
	char *	buffer = (char *)SvPV_nolen(ST(0));
	int	pos = (int)SvIV(ST(1));
	int	RETVAL;
	dXSTARG;
#line 235 "Nodave.xs"
	RETVAL = daveGetU16from(buffer+pos);
#line 591 "Nodave.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveGetS32from); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveGetS32from)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Nodave::daveGetS32from(buffer, pos)");
    {
	char *	buffer = (char *)SvPV_nolen(ST(0));
	int	pos = (int)SvIV(ST(1));
	int	RETVAL;
	dXSTARG;
#line 245 "Nodave.xs"
	RETVAL = daveGetS32from(buffer+pos);
#line 611 "Nodave.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveGetU32from); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveGetU32from)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Nodave::daveGetU32from(buffer, pos)");
    {
	char *	buffer = (char *)SvPV_nolen(ST(0));
	int	pos = (int)SvIV(ST(1));
	unsigned int	RETVAL;
	dXSTARG;
#line 255 "Nodave.xs"
	RETVAL = daveGetU32from(buffer+pos);
#line 631 "Nodave.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveGetFloatfrom); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveGetFloatfrom)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Nodave::daveGetFloatfrom(buffer, pos)");
    {
	char *	buffer = (char *)SvPV_nolen(ST(0));
	int	pos = (int)SvIV(ST(1));
	float	RETVAL;
	dXSTARG;
#line 265 "Nodave.xs"
	RETVAL = daveGetFloatfrom(buffer+pos);
#line 651 "Nodave.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveGetS8); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveGetS8)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Nodave::daveGetS8(dc)");
    {
	DaveConnection	dc;
	int	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "DaveConnection")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dc = INT2PTR(DaveConnection,tmp);
	}
	else
	    Perl_croak(aTHX_ "dc is not of type DaveConnection");
#line 274 "Nodave.xs"
	RETVAL = daveGetS8(dc);
#line 677 "Nodave.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveGetU8); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveGetU8)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Nodave::daveGetU8(dc)");
    {
	DaveConnection	dc;
	int	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "DaveConnection")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dc = INT2PTR(DaveConnection,tmp);
	}
	else
	    Perl_croak(aTHX_ "dc is not of type DaveConnection");
#line 283 "Nodave.xs"
	RETVAL = daveGetU8(dc);
#line 703 "Nodave.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveGetS16); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveGetS16)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Nodave::daveGetS16(dc)");
    {
	DaveConnection	dc;
	int	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "DaveConnection")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dc = INT2PTR(DaveConnection,tmp);
	}
	else
	    Perl_croak(aTHX_ "dc is not of type DaveConnection");
#line 293 "Nodave.xs"
	RETVAL = daveGetS16(dc);
#line 729 "Nodave.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveGetU16); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveGetU16)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Nodave::daveGetU16(dc)");
    {
	DaveConnection	dc;
	int	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "DaveConnection")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dc = INT2PTR(DaveConnection,tmp);
	}
	else
	    Perl_croak(aTHX_ "dc is not of type DaveConnection");
#line 303 "Nodave.xs"
	RETVAL = daveGetU16(dc);
#line 755 "Nodave.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveGetS32); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveGetS32)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Nodave::daveGetS32(dc)");
    {
	DaveConnection	dc;
	int	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "DaveConnection")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dc = INT2PTR(DaveConnection,tmp);
	}
	else
	    Perl_croak(aTHX_ "dc is not of type DaveConnection");
#line 313 "Nodave.xs"
	RETVAL = daveGetS32(dc);
#line 781 "Nodave.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveGetU32); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveGetU32)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Nodave::daveGetU32(dc)");
    {
	DaveConnection	dc;
	unsigned int	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "DaveConnection")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dc = INT2PTR(DaveConnection,tmp);
	}
	else
	    Perl_croak(aTHX_ "dc is not of type DaveConnection");
#line 323 "Nodave.xs"
	RETVAL = daveGetU32(dc);
#line 807 "Nodave.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveGetFloat); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveGetFloat)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Nodave::daveGetFloat(dc)");
    {
	DaveConnection	dc;
	float	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "DaveConnection")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dc = INT2PTR(DaveConnection,tmp);
	}
	else
	    Perl_croak(aTHX_ "dc is not of type DaveConnection");
#line 333 "Nodave.xs"
	RETVAL = daveGetFloat(dc);
#line 833 "Nodave.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveGetS8At); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveGetS8At)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Nodave::daveGetS8At(dc, pos)");
    {
	DaveConnection	dc;
	int	pos = (int)SvIV(ST(1));
	float	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "DaveConnection")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dc = INT2PTR(DaveConnection,tmp);
	}
	else
	    Perl_croak(aTHX_ "dc is not of type DaveConnection");
#line 343 "Nodave.xs"
	RETVAL = daveGetS8At(dc,pos);
#line 860 "Nodave.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveGetU8At); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveGetU8At)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Nodave::daveGetU8At(dc, pos)");
    {
	DaveConnection	dc;
	int	pos = (int)SvIV(ST(1));
	float	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "DaveConnection")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dc = INT2PTR(DaveConnection,tmp);
	}
	else
	    Perl_croak(aTHX_ "dc is not of type DaveConnection");
#line 353 "Nodave.xs"
	RETVAL = daveGetU8At(dc,pos);
#line 887 "Nodave.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveGetS16At); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveGetS16At)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Nodave::daveGetS16At(dc, pos)");
    {
	DaveConnection	dc;
	int	pos = (int)SvIV(ST(1));
	float	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "DaveConnection")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dc = INT2PTR(DaveConnection,tmp);
	}
	else
	    Perl_croak(aTHX_ "dc is not of type DaveConnection");
#line 363 "Nodave.xs"
	RETVAL = daveGetS16At(dc,pos);
#line 914 "Nodave.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveGetU16At); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveGetU16At)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Nodave::daveGetU16At(dc, pos)");
    {
	DaveConnection	dc;
	int	pos = (int)SvIV(ST(1));
	float	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "DaveConnection")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dc = INT2PTR(DaveConnection,tmp);
	}
	else
	    Perl_croak(aTHX_ "dc is not of type DaveConnection");
#line 373 "Nodave.xs"
	RETVAL = daveGetU16At(dc,pos);
#line 941 "Nodave.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveGetS32At); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveGetS32At)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Nodave::daveGetS32At(dc, pos)");
    {
	DaveConnection	dc;
	int	pos = (int)SvIV(ST(1));
	float	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "DaveConnection")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dc = INT2PTR(DaveConnection,tmp);
	}
	else
	    Perl_croak(aTHX_ "dc is not of type DaveConnection");
#line 383 "Nodave.xs"
	RETVAL = daveGetS32At(dc,pos);
#line 968 "Nodave.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveGetU32At); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveGetU32At)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Nodave::daveGetU32At(dc, pos)");
    {
	DaveConnection	dc;
	int	pos = (int)SvIV(ST(1));
	float	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "DaveConnection")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dc = INT2PTR(DaveConnection,tmp);
	}
	else
	    Perl_croak(aTHX_ "dc is not of type DaveConnection");
#line 393 "Nodave.xs"
	RETVAL = daveGetU32At(dc,pos);
#line 995 "Nodave.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveGetSeconds); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveGetSeconds)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Nodave::daveGetSeconds(dc)");
    {
	DaveConnection	dc;
	float	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "DaveConnection")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dc = INT2PTR(DaveConnection,tmp);
	}
	else
	    Perl_croak(aTHX_ "dc is not of type DaveConnection");
#line 402 "Nodave.xs"
	RETVAL = daveGetSeconds(dc);
#line 1021 "Nodave.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveGetSecondsAt); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveGetSecondsAt)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Nodave::daveGetSecondsAt(dc, pos)");
    {
	DaveConnection	dc;
	int	pos = (int)SvIV(ST(1));
	float	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "DaveConnection")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dc = INT2PTR(DaveConnection,tmp);
	}
	else
	    Perl_croak(aTHX_ "dc is not of type DaveConnection");
#line 412 "Nodave.xs"
	RETVAL = daveGetSecondsAt(dc,pos);
#line 1048 "Nodave.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveGetCounterValue); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveGetCounterValue)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Nodave::daveGetCounterValue(dc)");
    {
	DaveConnection	dc;
	float	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "DaveConnection")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dc = INT2PTR(DaveConnection,tmp);
	}
	else
	    Perl_croak(aTHX_ "dc is not of type DaveConnection");
#line 421 "Nodave.xs"
	RETVAL = daveGetCounterValue(dc);
#line 1074 "Nodave.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveGetCounterValueAt); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveGetCounterValueAt)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Nodave::daveGetCounterValueAt(dc, pos)");
    {
	DaveConnection	dc;
	int	pos = (int)SvIV(ST(1));
	float	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "DaveConnection")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dc = INT2PTR(DaveConnection,tmp);
	}
	else
	    Perl_croak(aTHX_ "dc is not of type DaveConnection");
#line 431 "Nodave.xs"
	RETVAL = daveGetCounterValueAt(dc,pos);
#line 1101 "Nodave.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveConnectPLC); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveConnectPLC)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Nodave::daveConnectPLC(dc)");
    {
	DaveConnection	dc;
	int	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "DaveConnection")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dc = INT2PTR(DaveConnection,tmp);
	}
	else
	    Perl_croak(aTHX_ "dc is not of type DaveConnection");
#line 443 "Nodave.xs"
	RETVAL = daveConnectPLC(dc);
#line 1127 "Nodave.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveReadBytes); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveReadBytes)
{
    dXSARGS;
    if (items != 5)
	Perl_croak(aTHX_ "Usage: Nodave::daveReadBytes(dc, area, areaNumber, start, bytes)");
    SP -= items;
    {
	DaveConnection	dc;
	int	area = (int)SvIV(ST(1));
	int	areaNumber = (int)SvIV(ST(2));
	int	start = (int)SvIV(ST(3));
	int	bytes = (int)SvIV(ST(4));

	if (sv_derived_from(ST(0), "DaveConnection")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dc = INT2PTR(DaveConnection,tmp);
	}
	else
	    Perl_croak(aTHX_ "dc is not of type DaveConnection");
#line 456 "Nodave.xs"
	char buffer[1024];
	int rv;
	rv = daveReadBytes (dc, area, areaNumber, start, bytes, buffer);
	EXTEND(SP,2);
	PUSHs(sv_2mortal(newSVpvn(&buffer[0],bytes)));
	PUSHs(sv_2mortal(newSViv(rv)));
#line 1161 "Nodave.c"
	PUTBACK;
	return;
    }
}


XS(XS_Nodave_daveWriteBytes); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveWriteBytes)
{
    dXSARGS;
    if (items != 6)
	Perl_croak(aTHX_ "Usage: Nodave::daveWriteBytes(dc, area, areaNumber, start, bytes, buffer)");
    {
	DaveConnection	dc;
	int	area = (int)SvIV(ST(1));
	int	areaNumber = (int)SvIV(ST(2));
	int	start = (int)SvIV(ST(3));
	int	bytes = (int)SvIV(ST(4));
	char*	buffer = (char *)SvPV_nolen(ST(5));
	int	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "DaveConnection")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dc = INT2PTR(DaveConnection,tmp);
	}
	else
	    Perl_croak(aTHX_ "dc is not of type DaveConnection");
#line 474 "Nodave.xs"
	RETVAL = daveWriteBytes (dc, area, areaNumber, start, bytes, buffer);
#line 1192 "Nodave.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveReadBits); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveReadBits)
{
    dXSARGS;
    if (items < 4 || items > 5)
	Perl_croak(aTHX_ "Usage: Nodave::daveReadBits(dc, area, areaNumber, start, bytes=1)");
    SP -= items;
    {
	DaveConnection	dc;
	int	area = (int)SvIV(ST(1));
	int	areaNumber = (int)SvIV(ST(2));
	int	start = (int)SvIV(ST(3));
	int	bytes;

	if (sv_derived_from(ST(0), "DaveConnection")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dc = INT2PTR(DaveConnection,tmp);
	}
	else
	    Perl_croak(aTHX_ "dc is not of type DaveConnection");

	if (items < 5)
	    bytes = 1;
	else {
	    bytes = (int)SvIV(ST(4));
	}
#line 487 "Nodave.xs"
	char buffer[1024];
	int rv;
	rv = daveReadBits (dc, area, areaNumber, start, bytes, buffer);
//	rv = daveReadBits (dc, area, areaNumber, start, bytes, NULL);
	EXTEND(SP,2);
	PUSHs(sv_2mortal(newSVpvn(&buffer[0],bytes)));
	PUSHs(sv_2mortal(newSViv(rv)));
#line 1233 "Nodave.c"
	PUTBACK;
	return;
    }
}


XS(XS_Nodave_daveWriteBits); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveWriteBits)
{
    dXSARGS;
    if (items != 6)
	Perl_croak(aTHX_ "Usage: Nodave::daveWriteBits(dc, area, areaNumber, start, bytes, buffer)");
    {
	DaveConnection	dc;
	int	area = (int)SvIV(ST(1));
	int	areaNumber = (int)SvIV(ST(2));
	int	start = (int)SvIV(ST(3));
	int	bytes = (int)SvIV(ST(4));
	char *	buffer = (char *)SvPV_nolen(ST(5));
	int	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "DaveConnection")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dc = INT2PTR(DaveConnection,tmp);
	}
	else
	    Perl_croak(aTHX_ "dc is not of type DaveConnection");
#line 505 "Nodave.xs"
	RETVAL = daveWriteBits (dc, area, areaNumber, start, bytes, buffer);
#line 1264 "Nodave.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveSetBit); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveSetBit)
{
    dXSARGS;
    if (items != 5)
	Perl_croak(aTHX_ "Usage: Nodave::daveSetBit(dc, area, DB, byteAdr, bitAdr)");
    {
	DaveConnection	dc;
	int	area = (int)SvIV(ST(1));
	int	DB = (int)SvIV(ST(2));
	int	byteAdr = (int)SvIV(ST(3));
	int	bitAdr = (int)SvIV(ST(4));
	int	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "DaveConnection")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dc = INT2PTR(DaveConnection,tmp);
	}
	else
	    Perl_croak(aTHX_ "dc is not of type DaveConnection");
#line 518 "Nodave.xs"
	RETVAL = daveSetBit (dc, area, DB, byteAdr, bitAdr);
#line 1294 "Nodave.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveClrBit); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveClrBit)
{
    dXSARGS;
    if (items != 5)
	Perl_croak(aTHX_ "Usage: Nodave::daveClrBit(dc, area, DB, byteAdr, bitAdr)");
    {
	DaveConnection	dc;
	int	area = (int)SvIV(ST(1));
	int	DB = (int)SvIV(ST(2));
	int	byteAdr = (int)SvIV(ST(3));
	int	bitAdr = (int)SvIV(ST(4));
	int	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "DaveConnection")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dc = INT2PTR(DaveConnection,tmp);
	}
	else
	    Perl_croak(aTHX_ "dc is not of type DaveConnection");
#line 531 "Nodave.xs"
	RETVAL = daveClrBit (dc, area, DB, byteAdr, bitAdr);
#line 1324 "Nodave.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveNewPDU); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveNewPDU)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Nodave::daveNewPDU()");
    {
	DavePDU	RETVAL;
#line 551 "Nodave.xs"
	RETVAL = daveNewPDU();
#line 1341 "Nodave.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "DavePDU", (void*)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveNewResultSet); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveNewResultSet)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Nodave::daveNewResultSet()");
    {
	DaveResultSet	RETVAL;
#line 560 "Nodave.xs"
	RETVAL = daveNewResultSet();
#line 1359 "Nodave.c"
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "DaveResultSet", (void*)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveInitAdapter); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveInitAdapter)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Nodave::daveInitAdapter(di)");
    {
	DaveInterface	di;
	int	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "DaveInterface")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    di = INT2PTR(DaveInterface,tmp);
	}
	else
	    Perl_croak(aTHX_ "di is not of type DaveInterface");
#line 572 "Nodave.xs"
	RETVAL = daveInitAdapter(di);
#line 1386 "Nodave.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveDisconnectPLC); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveDisconnectPLC)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Nodave::daveDisconnectPLC(dc)");
    {
	DaveConnection	dc;
	int	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "DaveConnection")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dc = INT2PTR(DaveConnection,tmp);
	}
	else
	    Perl_croak(aTHX_ "dc is not of type DaveConnection");
#line 583 "Nodave.xs"
	RETVAL = daveDisconnectPLC(dc);
#line 1412 "Nodave.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveDisconnectAdapter); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveDisconnectAdapter)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Nodave::daveDisconnectAdapter(di)");
    {
	DaveInterface	di;
	int	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "DaveInterface")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    di = INT2PTR(DaveInterface,tmp);
	}
	else
	    Perl_croak(aTHX_ "di is not of type DaveInterface");
#line 592 "Nodave.xs"
	RETVAL = daveDisconnectAdapter(di);
#line 1438 "Nodave.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveStop); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveStop)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Nodave::daveStop(dc)");
    {
	DaveConnection	dc;
	int	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "DaveConnection")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dc = INT2PTR(DaveConnection,tmp);
	}
	else
	    Perl_croak(aTHX_ "dc is not of type DaveConnection");
#line 607 "Nodave.xs"
	RETVAL = daveStop(dc);
#line 1464 "Nodave.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveStart); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveStart)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Nodave::daveStart(dc)");
    {
	DaveConnection	dc;
	int	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "DaveConnection")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dc = INT2PTR(DaveConnection,tmp);
	}
	else
	    Perl_croak(aTHX_ "dc is not of type DaveConnection");
#line 616 "Nodave.xs"
	RETVAL = daveStart(dc);
#line 1490 "Nodave.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_davePrepareReadRequest); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_davePrepareReadRequest)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Nodave::davePrepareReadRequest(dc, p)");
    {
	DaveConnection	dc;
	DavePDU	p;

	if (sv_derived_from(ST(0), "DaveConnection")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dc = INT2PTR(DaveConnection,tmp);
	}
	else
	    Perl_croak(aTHX_ "dc is not of type DaveConnection");

	if (sv_derived_from(ST(1), "DavePDU")) {
	    IV tmp = SvIV((SV*)SvRV(ST(1)));
	    p = INT2PTR(DavePDU,tmp);
	}
	else
	    Perl_croak(aTHX_ "p is not of type DavePDU");
#line 627 "Nodave.xs"
    davePrepareReadRequest(dc, p);
#line 1522 "Nodave.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Nodave_daveExecReadRequest); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveExecReadRequest)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Nodave::daveExecReadRequest(dc, p, rl)");
    {
	DaveConnection	dc;
	DavePDU	p;
	DaveResultSet	rl;
	int	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "DaveConnection")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dc = INT2PTR(DaveConnection,tmp);
	}
	else
	    Perl_croak(aTHX_ "dc is not of type DaveConnection");

	if (sv_derived_from(ST(1), "DavePDU")) {
	    IV tmp = SvIV((SV*)SvRV(ST(1)));
	    p = INT2PTR(DavePDU,tmp);
	}
	else
	    Perl_croak(aTHX_ "p is not of type DavePDU");

	if (sv_derived_from(ST(2), "DaveResultSet")) {
	    IV tmp = SvIV((SV*)SvRV(ST(2)));
	    rl = INT2PTR(DaveResultSet,tmp);
	}
	else
	    Perl_croak(aTHX_ "rl is not of type DaveResultSet");
#line 637 "Nodave.xs"
	RETVAL = daveExecReadRequest(dc, p, rl);
#line 1563 "Nodave.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveUseResult); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveUseResult)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Nodave::daveUseResult(dc, rl, n)");
    {
	DaveConnection	dc;
	DaveResultSet	rl;
	int	n = (int)SvIV(ST(2));
	int	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "DaveConnection")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dc = INT2PTR(DaveConnection,tmp);
	}
	else
	    Perl_croak(aTHX_ "dc is not of type DaveConnection");

	if (sv_derived_from(ST(1), "DaveResultSet")) {
	    IV tmp = SvIV((SV*)SvRV(ST(1)));
	    rl = INT2PTR(DaveResultSet,tmp);
	}
	else
	    Perl_croak(aTHX_ "rl is not of type DaveResultSet");
#line 647 "Nodave.xs"
	RETVAL = daveUseResult(dc, rl, n);
#line 1598 "Nodave.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveFreeResults); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveFreeResults)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Nodave::daveFreeResults(rl)");
    {
	DaveResultSet	rl;

	if (sv_derived_from(ST(0), "DaveResultSet")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    rl = INT2PTR(DaveResultSet,tmp);
	}
	else
	    Perl_croak(aTHX_ "rl is not of type DaveResultSet");
#line 655 "Nodave.xs"
	daveFreeResults(rl);
#line 1622 "Nodave.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Nodave_davePrepareWriteRequest); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_davePrepareWriteRequest)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Nodave::davePrepareWriteRequest(dc, p)");
    {
	DaveConnection	dc;
	DavePDU	p;

	if (sv_derived_from(ST(0), "DaveConnection")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dc = INT2PTR(DaveConnection,tmp);
	}
	else
	    Perl_croak(aTHX_ "dc is not of type DaveConnection");

	if (sv_derived_from(ST(1), "DavePDU")) {
	    IV tmp = SvIV((SV*)SvRV(ST(1)));
	    p = INT2PTR(DavePDU,tmp);
	}
	else
	    Perl_croak(aTHX_ "p is not of type DavePDU");
#line 662 "Nodave.xs"
	davePrepareWriteRequest(dc, p);
#line 1653 "Nodave.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Nodave_daveAddVarToWriteRequest); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveAddVarToWriteRequest)
{
    dXSARGS;
    if (items != 6)
	Perl_croak(aTHX_ "Usage: Nodave::daveAddVarToWriteRequest(p, area, DBnum, start, bytes, buffer)");
    {
	DavePDU	p;
	int	area = (int)SvIV(ST(1));
	int	DBnum = (int)SvIV(ST(2));
	int	start = (int)SvIV(ST(3));
	int	bytes = (int)SvIV(ST(4));
	char*	buffer = (char *)SvPV_nolen(ST(5));

	if (sv_derived_from(ST(0), "DavePDU")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    p = INT2PTR(DavePDU,tmp);
	}
	else
	    Perl_croak(aTHX_ "p is not of type DavePDU");
#line 673 "Nodave.xs"
    daveAddVarToWriteRequest(p, area, DBnum, start, bytes, buffer);
#line 1681 "Nodave.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Nodave_daveAddBitVarToWriteRequest); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveAddBitVarToWriteRequest)
{
    dXSARGS;
    if (items != 6)
	Perl_croak(aTHX_ "Usage: Nodave::daveAddBitVarToWriteRequest(p, area, DBnum, start, bytes, buffer)");
    {
	DavePDU	p;
	int	area = (int)SvIV(ST(1));
	int	DBnum = (int)SvIV(ST(2));
	int	start = (int)SvIV(ST(3));
	int	bytes = (int)SvIV(ST(4));
	char*	buffer = (char *)SvPV_nolen(ST(5));

	if (sv_derived_from(ST(0), "DavePDU")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    p = INT2PTR(DavePDU,tmp);
	}
	else
	    Perl_croak(aTHX_ "p is not of type DavePDU");
#line 684 "Nodave.xs"
    daveAddBitVarToWriteRequest(p, area, DBnum, start, bytes, buffer);
#line 1709 "Nodave.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Nodave_daveAddVarToReadRequest); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveAddVarToReadRequest)
{
    dXSARGS;
    if (items != 5)
	Perl_croak(aTHX_ "Usage: Nodave::daveAddVarToReadRequest(p, area, DBnum, start, bytes)");
    {
	DavePDU	p;
	int	area = (int)SvIV(ST(1));
	int	DBnum = (int)SvIV(ST(2));
	int	start = (int)SvIV(ST(3));
	int	bytes = (int)SvIV(ST(4));

	if (sv_derived_from(ST(0), "DavePDU")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    p = INT2PTR(DavePDU,tmp);
	}
	else
	    Perl_croak(aTHX_ "p is not of type DavePDU");
#line 694 "Nodave.xs"
    daveAddVarToReadRequest(p, area, DBnum, start, bytes);
#line 1736 "Nodave.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Nodave_daveAddBitVarToReadRequest); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveAddBitVarToReadRequest)
{
    dXSARGS;
    if (items != 5)
	Perl_croak(aTHX_ "Usage: Nodave::daveAddBitVarToReadRequest(p, area, DBnum, start, bytes)");
    {
	DavePDU	p;
	int	area = (int)SvIV(ST(1));
	int	DBnum = (int)SvIV(ST(2));
	int	start = (int)SvIV(ST(3));
	int	bytes = (int)SvIV(ST(4));

	if (sv_derived_from(ST(0), "DavePDU")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    p = INT2PTR(DavePDU,tmp);
	}
	else
	    Perl_croak(aTHX_ "p is not of type DavePDU");
#line 704 "Nodave.xs"
    daveAddBitVarToReadRequest(p, area, DBnum, start, bytes);
#line 1763 "Nodave.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Nodave_setPort); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_setPort)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Nodave::setPort(port, baud, parity)");
    {
	char*	port = (char *)SvPV_nolen(ST(0));
	char*	baud = (char *)SvPV_nolen(ST(1));
	char	parity = (char)*SvPV_nolen(ST(2));
	int	RETVAL;
	dXSTARG;
#line 713 "Nodave.xs"
	RETVAL = setPort(port, baud, parity);
#line 1783 "Nodave.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_openSocket); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_openSocket)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Nodave::openSocket(port, peer)");
    {
	int	port = (int)SvIV(ST(0));
	char*	peer = (char *)SvPV_nolen(ST(1));
	int	RETVAL;
	dXSTARG;
#line 723 "Nodave.xs"
	RETVAL = openSocket(port, peer);
#line 1803 "Nodave.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_closePort); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_closePort)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Nodave::closePort(port)");
    {
	int	port = (int)SvIV(ST(0));
	int	RETVAL;
	dXSTARG;
#line 732 "Nodave.xs"
	RETVAL = closePort(port);
#line 1822 "Nodave.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveGetTimeout); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveGetTimeout)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Nodave::daveGetTimeout(di)");
    {
	DaveInterface	di;
	int	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "DaveInterface")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    di = INT2PTR(DaveInterface,tmp);
	}
	else
	    Perl_croak(aTHX_ "di is not of type DaveInterface");
#line 741 "Nodave.xs"
	RETVAL = daveGetTimeout(di);
#line 1848 "Nodave.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveSetTimeout); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveSetTimeout)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Nodave::daveSetTimeout(di, time)");
    {
	DaveInterface	di;
	int	time = (int)SvIV(ST(1));

	if (sv_derived_from(ST(0), "DaveInterface")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    di = INT2PTR(DaveInterface,tmp);
	}
	else
	    Perl_croak(aTHX_ "di is not of type DaveInterface");
#line 751 "Nodave.xs"
	daveSetTimeout(di, time);
#line 1873 "Nodave.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Nodave_daveGetName); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveGetName)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Nodave::daveGetName(di)");
    {
	DaveInterface	di;
	char *	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "DaveInterface")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    di = INT2PTR(DaveInterface,tmp);
	}
	else
	    Perl_croak(aTHX_ "di is not of type DaveInterface");
#line 758 "Nodave.xs"
	RETVAL = daveGetName(di);
#line 1898 "Nodave.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveGetAnswLen); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveGetAnswLen)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Nodave::daveGetAnswLen(dc)");
    {
	DaveConnection	dc;
	int	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "DaveConnection")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dc = INT2PTR(DaveConnection,tmp);
	}
	else
	    Perl_croak(aTHX_ "dc is not of type DaveConnection");
#line 767 "Nodave.xs"
	RETVAL = daveGetAnswLen(dc);
#line 1924 "Nodave.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveGetMaxPDULen); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveGetMaxPDULen)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Nodave::daveGetMaxPDULen(dc)");
    {
	DaveConnection	dc;
	int	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "DaveConnection")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dc = INT2PTR(DaveConnection,tmp);
	}
	else
	    Perl_croak(aTHX_ "dc is not of type DaveConnection");
#line 776 "Nodave.xs"
	RETVAL = daveGetMaxPDULen(dc);
#line 1950 "Nodave.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveGetMPIAdr); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveGetMPIAdr)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Nodave::daveGetMPIAdr(dc)");
    {
	DaveConnection	dc;
	int	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "DaveConnection")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dc = INT2PTR(DaveConnection,tmp);
	}
	else
	    Perl_croak(aTHX_ "dc is not of type DaveConnection");
#line 785 "Nodave.xs"
	RETVAL = daveGetMPIAdr(dc);
#line 1976 "Nodave.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveGetErrorOfResult); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveGetErrorOfResult)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Nodave::daveGetErrorOfResult(drs, n)");
    {
	DaveResultSet	drs;
	int	n = (int)SvIV(ST(1));
	int	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "DaveResultSet")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    drs = INT2PTR(DaveResultSet,tmp);
	}
	else
	    Perl_croak(aTHX_ "drs is not of type DaveResultSet");
#line 795 "Nodave.xs"
	RETVAL = daveGetErrorOfResult (drs, n);
#line 2003 "Nodave.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveForceDisconnectIBH); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveForceDisconnectIBH)
{
    dXSARGS;
    if (items != 4)
	Perl_croak(aTHX_ "Usage: Nodave::daveForceDisconnectIBH(di, src, dest, mpi)");
    {
	DaveInterface	di;
	int	src = (int)SvIV(ST(1));
	int	dest = (int)SvIV(ST(2));
	int	mpi = (int)SvIV(ST(3));
	int	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "DaveInterface")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    di = INT2PTR(DaveInterface,tmp);
	}
	else
	    Perl_croak(aTHX_ "di is not of type DaveInterface");
#line 807 "Nodave.xs"
	RETVAL = daveForceDisconnectIBH (di,src,dest,mpi);
#line 2032 "Nodave.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveForce200); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveForce200)
{
    dXSARGS;
    if (items != 4)
	Perl_croak(aTHX_ "Usage: Nodave::daveForce200(dc, area, start, val)");
    {
	DaveConnection	dc;
	int	area = (int)SvIV(ST(1));
	int	start = (int)SvIV(ST(2));
	int	val = (int)SvIV(ST(3));
	int	RETVAL;
	dXSTARG;

	if (sv_derived_from(ST(0), "DaveConnection")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dc = INT2PTR(DaveConnection,tmp);
	}
	else
	    Perl_croak(aTHX_ "dc is not of type DaveConnection");
#line 819 "Nodave.xs"
	RETVAL = daveForce200 (dc, area, start, val);
#line 2061 "Nodave.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Nodave_daveGetOrderCode); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveGetOrderCode)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Nodave::daveGetOrderCode(dc)");
    SP -= items;
    {
	DaveConnection	dc;

	if (sv_derived_from(ST(0), "DaveConnection")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dc = INT2PTR(DaveConnection,tmp);
	}
	else
	    Perl_croak(aTHX_ "dc is not of type DaveConnection");
#line 828 "Nodave.xs"
	char buffer[1024];
	int rv;
	rv = daveGetOrderCode(dc, buffer);
	EXTEND(SP,2);
	PUSHs(sv_2mortal(newSVpvn(&buffer[0],daveOrderCodeSize)));
	PUSHs(sv_2mortal(newSViv(rv)));
#line 2091 "Nodave.c"
	PUTBACK;
	return;
    }
}


XS(XS_Nodave_daveReadSZL); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveReadSZL)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Nodave::daveReadSZL(dc, ID, index)");
    SP -= items;
    {
	DaveConnection	dc;
	int	ID = (int)SvIV(ST(1));
	int	index = (int)SvIV(ST(2));

	if (sv_derived_from(ST(0), "DaveConnection")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dc = INT2PTR(DaveConnection,tmp);
	}
	else
	    Perl_croak(aTHX_ "dc is not of type DaveConnection");
#line 841 "Nodave.xs"
	char buffer[3000];
	int rv;
	rv = daveReadSZL(dc, ID, index, buffer, 3000);
	EXTEND(SP,2);
	PUSHs(sv_2mortal(newSVpvn(&buffer[0],daveOrderCodeSize)));
	PUSHs(sv_2mortal(newSViv(rv)));
#line 2123 "Nodave.c"
	PUTBACK;
	return;
    }
}


XS(XS_Nodave_daveListReachablePartners); /* prototype to pass -Wmissing-prototypes */
XS(XS_Nodave_daveListReachablePartners)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Nodave::daveListReachablePartners(di)");
    SP -= items;
    {
	DaveInterface	di;

	if (sv_derived_from(ST(0), "DaveInterface")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    di = INT2PTR(DaveInterface,tmp);
	}
	else
	    Perl_croak(aTHX_ "di is not of type DaveInterface");
#line 852 "Nodave.xs"
	char buffer[126];
	int rv;
	rv = daveListReachablePartners(di, buffer);
	EXTEND(SP,2);
	PUSHs(sv_2mortal(newSVpvn(&buffer[0],daveOrderCodeSize)));
	PUSHs(sv_2mortal(newSViv(rv)));
#line 2153 "Nodave.c"
	PUTBACK;
	return;
    }
}


XS(XS_DaveInterface_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS(XS_DaveInterface_DESTROY)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: DaveInterface::DESTROY(di)");
    {
	DaveInterface	di;

	if (SvROK(ST(0))) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    di = INT2PTR(DaveInterface,tmp);
	}
	else
	    Perl_croak(aTHX_ "di is not a reference");
#line 864 "Nodave.xs"
//	printf("freeing DaveInterface %p\n",di);
	daveFree(di);
#line 2178 "Nodave.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_DaveConnection_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS(XS_DaveConnection_DESTROY)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: DaveConnection::DESTROY(dc)");
    {
	DaveConnection	dc;

	if (SvROK(ST(0))) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dc = INT2PTR(DaveConnection,tmp);
	}
	else
	    Perl_croak(aTHX_ "dc is not a reference");
#line 872 "Nodave.xs"
//	printf("freeing DaveConnection %p\n",dc);
	daveFree(dc);	
#line 2202 "Nodave.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_DavePDU_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS(XS_DavePDU_DESTROY)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: DavePDU::DESTROY(dp)");
    {
	DavePDU	dp;

	if (SvROK(ST(0))) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    dp = INT2PTR(DavePDU,tmp);
	}
	else
	    Perl_croak(aTHX_ "dp is not a reference");
#line 880 "Nodave.xs"
//	printf("freeing DavePDU %p\n",dp);
	daveFree(dp);	
#line 2226 "Nodave.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_DaveResultSet_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS(XS_DaveResultSet_DESTROY)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: DaveResultSet::DESTROY(drs)");
    {
	DaveResultSet	drs;

	if (SvROK(ST(0))) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    drs = INT2PTR(DaveResultSet,tmp);
	}
	else
	    Perl_croak(aTHX_ "drs is not a reference");
#line 888 "Nodave.xs"
//	printf("freeing DaveResultSet %p\n",drs);
	daveFreeResults(drs);
	daveFree(drs);	
#line 2251 "Nodave.c"
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Nodave); /* prototype to pass -Wmissing-prototypes */
XS(boot_Nodave)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXS("Nodave::constant", XS_Nodave_constant, file);
        newXSproto("Nodave::daveStrerror", XS_Nodave_daveStrerror, file, "$");
        newXSproto("Nodave::daveSetDebug", XS_Nodave_daveSetDebug, file, "$");
        newXSproto("Nodave::daveGetDebug", XS_Nodave_daveGetDebug, file, "");
        newXSproto("Nodave::daveNewInterface", XS_Nodave_daveNewInterface, file, "$$$$$$");
        newXSproto("Nodave::daveNewConnection", XS_Nodave_daveNewConnection, file, "$$$$");
        newXSproto("Nodave::daveGetResponse", XS_Nodave_daveGetResponse, file, "$");
        newXSproto("Nodave::daveSendMessage", XS_Nodave_daveSendMessage, file, "$");
        newXSproto("Nodave::daveDumpPDU", XS_Nodave_daveDumpPDU, file, "$");
        newXSproto("Nodave::daveDump", XS_Nodave_daveDump, file, "$$$");
        newXSproto("Nodave::daveBlockName", XS_Nodave_daveBlockName, file, "$");
        newXSproto("Nodave::daveAreaName", XS_Nodave_daveAreaName, file, "$");
        newXSproto("Nodave::daveSwapIed_16", XS_Nodave_daveSwapIed_16, file, "$");
        newXSproto("Nodave::daveSwapIed_32", XS_Nodave_daveSwapIed_32, file, "$");
        newXSproto("Nodave::daveGetFloatAt", XS_Nodave_daveGetFloatAt, file, "$$");
        newXSproto("Nodave::toPLCfloat", XS_Nodave_toPLCfloat, file, "$");
        newXSproto("Nodave::daveToPLCfloat", XS_Nodave_daveToPLCfloat, file, "$");
        newXSproto("Nodave::daveGetS8from", XS_Nodave_daveGetS8from, file, "$$");
        newXSproto("Nodave::daveGetU8from", XS_Nodave_daveGetU8from, file, "$$");
        newXSproto("Nodave::daveGetS16from", XS_Nodave_daveGetS16from, file, "$$");
        newXSproto("Nodave::daveGetU16from", XS_Nodave_daveGetU16from, file, "$$");
        newXSproto("Nodave::daveGetS32from", XS_Nodave_daveGetS32from, file, "$$");
        newXSproto("Nodave::daveGetU32from", XS_Nodave_daveGetU32from, file, "$$");
        newXSproto("Nodave::daveGetFloatfrom", XS_Nodave_daveGetFloatfrom, file, "$$");
        newXSproto("Nodave::daveGetS8", XS_Nodave_daveGetS8, file, "$");
        newXSproto("Nodave::daveGetU8", XS_Nodave_daveGetU8, file, "$");
        newXSproto("Nodave::daveGetS16", XS_Nodave_daveGetS16, file, "$");
        newXSproto("Nodave::daveGetU16", XS_Nodave_daveGetU16, file, "$");
        newXSproto("Nodave::daveGetS32", XS_Nodave_daveGetS32, file, "$");
        newXSproto("Nodave::daveGetU32", XS_Nodave_daveGetU32, file, "$");
        newXSproto("Nodave::daveGetFloat", XS_Nodave_daveGetFloat, file, "$");
        newXSproto("Nodave::daveGetS8At", XS_Nodave_daveGetS8At, file, "$$");
        newXSproto("Nodave::daveGetU8At", XS_Nodave_daveGetU8At, file, "$$");
        newXSproto("Nodave::daveGetS16At", XS_Nodave_daveGetS16At, file, "$$");
        newXSproto("Nodave::daveGetU16At", XS_Nodave_daveGetU16At, file, "$$");
        newXSproto("Nodave::daveGetS32At", XS_Nodave_daveGetS32At, file, "$$");
        newXSproto("Nodave::daveGetU32At", XS_Nodave_daveGetU32At, file, "$$");
        newXSproto("Nodave::daveGetSeconds", XS_Nodave_daveGetSeconds, file, "$$");
        newXSproto("Nodave::daveGetSecondsAt", XS_Nodave_daveGetSecondsAt, file, "$$");
        newXSproto("Nodave::daveGetCounterValue", XS_Nodave_daveGetCounterValue, file, "$$");
        newXSproto("Nodave::daveGetCounterValueAt", XS_Nodave_daveGetCounterValueAt, file, "$$");
        newXSproto("Nodave::daveConnectPLC", XS_Nodave_daveConnectPLC, file, "$");
        newXSproto("Nodave::daveReadBytes", XS_Nodave_daveReadBytes, file, "$$$$$");
        newXSproto("Nodave::daveWriteBytes", XS_Nodave_daveWriteBytes, file, "$$$$$$");
        newXSproto("Nodave::daveReadBits", XS_Nodave_daveReadBits, file, "$$$$;$");
        newXSproto("Nodave::daveWriteBits", XS_Nodave_daveWriteBits, file, "$$$$$$");
        newXSproto("Nodave::daveSetBit", XS_Nodave_daveSetBit, file, "$$$$$");
        newXSproto("Nodave::daveClrBit", XS_Nodave_daveClrBit, file, "$$$$$");
        newXSproto("Nodave::daveNewPDU", XS_Nodave_daveNewPDU, file, "");
        newXSproto("Nodave::daveNewResultSet", XS_Nodave_daveNewResultSet, file, "");
        newXSproto("Nodave::daveInitAdapter", XS_Nodave_daveInitAdapter, file, "$");
        newXSproto("Nodave::daveDisconnectPLC", XS_Nodave_daveDisconnectPLC, file, "$");
        newXSproto("Nodave::daveDisconnectAdapter", XS_Nodave_daveDisconnectAdapter, file, "$");
        newXSproto("Nodave::daveStop", XS_Nodave_daveStop, file, "$");
        newXSproto("Nodave::daveStart", XS_Nodave_daveStart, file, "$");
        newXSproto("Nodave::davePrepareReadRequest", XS_Nodave_davePrepareReadRequest, file, "$$");
        newXSproto("Nodave::daveExecReadRequest", XS_Nodave_daveExecReadRequest, file, "$$$");
        newXSproto("Nodave::daveUseResult", XS_Nodave_daveUseResult, file, "$$$");
        newXSproto("Nodave::daveFreeResults", XS_Nodave_daveFreeResults, file, "$");
        newXSproto("Nodave::davePrepareWriteRequest", XS_Nodave_davePrepareWriteRequest, file, "$$");
        newXSproto("Nodave::daveAddVarToWriteRequest", XS_Nodave_daveAddVarToWriteRequest, file, "$$$$$$");
        newXSproto("Nodave::daveAddBitVarToWriteRequest", XS_Nodave_daveAddBitVarToWriteRequest, file, "$$$$$$");
        newXSproto("Nodave::daveAddVarToReadRequest", XS_Nodave_daveAddVarToReadRequest, file, "$$$$$");
        newXSproto("Nodave::daveAddBitVarToReadRequest", XS_Nodave_daveAddBitVarToReadRequest, file, "$$$$$");
        newXSproto("Nodave::setPort", XS_Nodave_setPort, file, "$$$");
        newXSproto("Nodave::openSocket", XS_Nodave_openSocket, file, "$$");
        newXSproto("Nodave::closePort", XS_Nodave_closePort, file, "$");
        newXSproto("Nodave::daveGetTimeout", XS_Nodave_daveGetTimeout, file, "$");
        newXSproto("Nodave::daveSetTimeout", XS_Nodave_daveSetTimeout, file, "$$");
        newXSproto("Nodave::daveGetName", XS_Nodave_daveGetName, file, "$");
        newXSproto("Nodave::daveGetAnswLen", XS_Nodave_daveGetAnswLen, file, "$");
        newXSproto("Nodave::daveGetMaxPDULen", XS_Nodave_daveGetMaxPDULen, file, "$");
        newXSproto("Nodave::daveGetMPIAdr", XS_Nodave_daveGetMPIAdr, file, "$");
        newXSproto("Nodave::daveGetErrorOfResult", XS_Nodave_daveGetErrorOfResult, file, "$$");
        newXSproto("Nodave::daveForceDisconnectIBH", XS_Nodave_daveForceDisconnectIBH, file, "$$$$");
        newXSproto("Nodave::daveForce200", XS_Nodave_daveForce200, file, "$$$$");
        newXSproto("Nodave::daveGetOrderCode", XS_Nodave_daveGetOrderCode, file, "$");
        newXSproto("Nodave::daveReadSZL", XS_Nodave_daveReadSZL, file, "$$$");
        newXSproto("Nodave::daveListReachablePartners", XS_Nodave_daveListReachablePartners, file, "$");
        newXS("DaveInterface::DESTROY", XS_DaveInterface_DESTROY, file);
        newXS("DaveConnection::DESTROY", XS_DaveConnection_DESTROY, file);
        newXS("DavePDU::DESTROY", XS_DavePDU_DESTROY, file);
        newXS("DaveResultSet::DESTROY", XS_DaveResultSet_DESTROY, file);
    XSRETURN_YES;
}

